name: Sync Upstream

on:
  #push:
  #  branches:
  #    - main
  #schedule:
  #  - cron: "10 * * * *" # Execute at 10 minutes past the hour.
  workflow_dispatch: # allow manually trigger the action

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # Job-level permissions configuration starts here
      contents: write # 'write' access to repository contents
      pull-requests: write # 'write' access to pull requests
    env:
      GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
      MYSTEN_SPREEDSHEET_ID: ${{ secrets.MYSTEN_SPREEDSHEET_ID }}
      BLOCKLISTS_URL: ${{ secrets.BLOCKLISTS_URL }}
      ALLOWLISTS_URL: ${{ secrets.ALLOWLISTS_URL }}
      READ_ACCESS_TOKEN: ${{ secrets.READ_ACCESS_TOKEN }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Use the GitHub checkout action to checkout code

      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install dependencies using PNPM
        run: pnpm install

      - name: Sync blocklists
        run: pnpm sync-blocklists

      - name: Sync allowlists
        run: pnpm sync-allowlists
      
      - name: Copy blocklists to src
        run: cp -rf blocklists/*.json src/

      - name: Commit changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "Auto-update from script" || echo "No changes to commit"
          git push
